export { default as Header } from "./Header";
export { default as Banner } from "./Banner";
export { default as Services } from "./Services";
export { default as Features } from "./Features";
export { default as People } from "./People";
export { default as Testim } from "./Testim";
export { default as Footer } from "./Footer";
export { default as StarRate } from "./StarRate";
export { default as Product } from "./Product";
